name: Parsing markets

on:
#  push:
  workflow_dispatch:
  schedule:
    - cron: '00 10 * * *'
#    - cron: '10 06 * * *'

jobs:
  tests:
    name: I. Building environment and run markets parsing
#     runs-on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - name: 1. Check out this repo, master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: 2.1. Install Python
        if: always()
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: 4. install Poetry
        if: always()
        run: pip3 install poetry

      - name: 5. install dependencies
        if: always()
        run: poetry install --sync

      - name: 8. Run Markets parsing
        if: always()
#        run: poetry run pytest --no-summary -vv --env=github tests/TradingView/Parsing/markets_parsing.py
        run: poetry run pytest -vv --env=github tests/TradingView/Parsing/markets_parsing.py
        continue-on-error: true
